services:
  load-balancer:
    container_name: load-balancer
    build:
      context: .
      dockerfile: Dockerfile

  mysql-node-01:
    container_name: mysql-node-01
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306

  mysql-node-02:
    container_name: mysql-node-02
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306

  load-balancer-mysql-dashboard:
    container_name: load-balancer-mysql-dashboard
    image: phpmyadmin/phpmyadmin
    ports:
      - 9091:80
    environment:
      PMA_HOST: load-balancer
      PMA_PORT: 3305
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_DATABASE: test

  node-01-mysql-dashboard:
    container_name: node-01-mysql-dashboard
    image: phpmyadmin/phpmyadmin
    ports:
      - 9092:80
    environment:
      PMA_HOST: mysql-node-01
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_DATABASE: test

  node-02-mysql-dashboard:
    container_name: node-02-mysql-dashboard
    image: phpmyadmin/phpmyadmin
    ports:
      - 9093:80
    environment:
      PMA_HOST: mysql-node-02
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_DATABASE: test
