services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: caching_backend

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 8060:8060
    depends_on:
      - backend
    container_name: caching_proxy
